services:
  localstack:
    container_name: fintrack-localstack
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      PERSISTENCE: 1
    volumes:
      - localstack-data:/var/lib/localstack

volumes:
  localstack-data: