spring.application.name=worker-service
spring.main.web-application-type=none

fintrack.sqs.transaction-processing-queue=fintrack-transaction-processing

spring.datasource.url=jdbc:postgresql://localhost:5432/fintrack
spring.datasource.username=fintrack
spring.datasource.password=fintrack